# Generated by Django 5.2.17 on 2026-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], verbose_name='Класс')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Оставлена')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'заявка на консультацию',
                'verbose_name_plural': 'заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
