# Generated by Django 5.2.17 on 2026-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], null=True, verbose_name='Класс'),
        ),
    ]
