# Generated by Django 5.2.17 on 2026-09-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Оставлена')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ссылка выдана')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'заявка на смену пароля',
                'verbose_name_plural': 'заявки на смену пароля',
                'ordering': ['-created_at'],
            },
        ),
    ]
