# Generated by Django 5.2.17 on 2026-09-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entry', 'Входной тест'), ('final', 'Итоговый тест')], max_length=10)),
                ('question_ids', models.JSONField(default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='children.child')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('passed', 'Пройдена'), ('needs_repeat', 'Нужно повторить')], default='not_started', max_length=20)),
                ('stage', models.CharField(choices=[('entry_test', 'Входной тест'), ('material', 'Материал'), ('final_test', 'Итоговый тест'), ('done', 'Цикл завершён')], default='entry_test', max_length=20)),
                ('entry_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='children.child')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='curriculum.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'topic'), name='progress_unique_child_topic')],
            },
        ),
    ]
