# Generated by Django 5.2.17 on 2026-09-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.section')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(choices=[('entry', 'Входной тест'), ('final', 'Итоговый тест')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculum.topic')),
            ],
            options={
                'ordering': ['topic', 'pool', 'order'],
                'constraints': [models.UniqueConstraint(fields=('topic', 'pool', 'order'), name='question_unique_order_in_pool')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True)),
                ('summary_md', models.TextField()),
                ('summary_html', models.TextField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='curriculum.topic')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('summary_md', ''), _negated=True), name='material_summary_required')],
            },
        ),
    ]
