# Generated by Django 5.2.17 on 2026-09-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_section_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic', 'pool', 'order'], 'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'id'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'id'], 'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
    ]
