# Generated by Django 5.2.17 on 2026-09-24 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_material_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='parent_guide_html',
            field=models.TextField(blank=True, verbose_name='сценарий в HTML'),
        ),
        migrations.AlterField(
            model_name='material',
            name='parent_guide_md',
            field=models.TextField(help_text='Обязательно: сценарий для родителя — что сказать, о чём спросить, что делать при ошибке', verbose_name='как провести занятие (Markdown)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='summary_html',
            field=models.TextField(blank=True, verbose_name='конспект в HTML'),
        ),
        migrations.AlterField(
            model_name='material',
            name='summary_md',
            field=models.TextField(help_text='Обязателен: при слабом интернете он заменяет видео', verbose_name='конспект (Markdown)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='curriculum.topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='Необязательно', verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_index',
            field=models.PositiveSmallIntegerField(help_text='Считается с нуля: первый вариант — 0, второй — 1', verbose_name='номер правильного варианта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Показывается в разборе ошибок', verbose_name='объяснение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(help_text='Список в кавычках, например: ["9", "10", "11"]', verbose_name='варианты ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(verbose_name='порядок в тесте'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pool',
            field=models.CharField(choices=[('entry', 'Входной тест'), ('final', 'Итоговый тест')], max_length=10, verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='текст задания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculum.topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание на карточке'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок в каталоге'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(help_text='Латиницей, например math или english', unique=True, verbose_name='адрес в ссылке'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок в курсе'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.section', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(help_text='Латиницей, например simple-arithmetic', unique=True, verbose_name='адрес в ссылке'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название темы'),
        ),
    ]
